"""Persist IM run/checkpoints and align dispatch indexes and error text type.

Revision ID: 95297fe46655
Revises: a4c8e6d1f9b2
Create Date: 2026-09-12 18:43:52.754820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = "95297fe46655"
down_revision: Union[str, Sequence[str], None] = "a4c8e6d1f9b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agentcore_dispatches",
        "error_message",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_agentcore_dispatches_org_id"), "agentcore_dispatches", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_agentcore_dispatches_run_id"), "agentcore_dispatches", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_agentcore_dispatches_status"), "agentcore_dispatches", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_agentcore_dispatches_workspace_id"),
        "agentcore_dispatches",
        ["workspace_id"],
        unique=False,
    )
    op.add_column(
        "im_run_queue",
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    )
    op.add_column("im_run_queue", sa.Column("outbound_state", sa.JSON(), nullable=True))
    op.create_index(op.f("ix_im_run_queue_run_id"), "im_run_queue", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_im_run_queue_run_id"), table_name="im_run_queue")
    op.drop_column("im_run_queue", "outbound_state")
    op.drop_column("im_run_queue", "run_id")
    op.drop_index(op.f("ix_agentcore_dispatches_workspace_id"), table_name="agentcore_dispatches")
    op.drop_index(op.f("ix_agentcore_dispatches_status"), table_name="agentcore_dispatches")
    op.drop_index(op.f("ix_agentcore_dispatches_run_id"), table_name="agentcore_dispatches")
    op.drop_index(op.f("ix_agentcore_dispatches_org_id"), table_name="agentcore_dispatches")
    op.alter_column(
        "agentcore_dispatches",
        "error_message",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
