"""Align AgentCore response claim uniqueness

Revision ID: 9d1eb1d17321
Revises: 95297fe46655
Create Date: 2026-09-12 19:41:54.611506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = '9d1eb1d17321'
down_revision: Union[str, Sequence[str], None] = '95297fe46655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_agentcore_dispatch_respond_claim'), table_name='agentcore_dispatches', postgresql_where="((operation)::text = 'respond'::text)")
    op.create_index('uq_agentcore_dispatch_respond_claim', 'agentcore_dispatches', ['claim_token'], unique=True, postgresql_where=sa.text("operation = 'respond'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_agentcore_dispatch_respond_claim', table_name='agentcore_dispatches', postgresql_where=sa.text("operation = 'respond'"))
    op.create_index(op.f('uq_agentcore_dispatch_respond_claim'), 'agentcore_dispatches', ['run_id', 'operation', 'claim_token'], unique=True, postgresql_where="((operation)::text = 'respond'::text)")
    # ### end Alembic commands ###
