"""add native agentcore callback receipts

Revision ID: c3fd20f6c1d6
Revises: 9d1eb1d17321
Create Date: 2026-09-13 20:37:47.651480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3fd20f6c1d6'
down_revision: Union[str, Sequence[str], None] = '9d1eb1d17321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentcore_callbacks',
    sa.Column('dispatch_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('payload_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['agentcore_dispatches.id'], ),
    sa.PrimaryKeyConstraint('dispatch_id', 'request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agentcore_callbacks')
    # ### end Alembic commands ###
